/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GameState */

#ifndef _Included_GameState
#define _Included_GameState
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GameState
 * Method:    intMethod
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_GameState_intMethod
  (JNIEnv *, jobject);

/*
 * Class:     GameState
 * Method:    strMethod
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_GameState_strMethod
  (JNIEnv *, jobject);

/*
 * Class:     GameState
 * Method:    voidMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GameState_voidMethod
  (JNIEnv *, jobject);

/*
 * Class:     GameState
 * Method:    drawImage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GameState_drawImage
  (JNIEnv *, jobject);

/*
 * Class:     GameState
 * Method:    Physics
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GameState_Physics
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
